### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by tdurieux**

### CODE REVIEW

**Comment by fermadeiral** [comment]
LGTM. I will merge it after everyone agrees with that.

@victor-sobreira, @monperrus, @maiamarcelo, WDYT?

**Comment by monperrus** [comment]
OK for me.

**Comment by maiamarcelo** [comment]
I’m ok with that too.
[]s
Marcelo
UFU-FACOM

**Comment by victor-sobreira** [comment]
👍

Em ter, 10 de set de 2019 08:44, Marcelo Maia <notifications@github.com>
escreveu:

**Pull request merged**
